version: '3'
services:
  backend:
    build:
      context: ./Backend
    ports:
      - "3000:3000"
    networks:
      cyber:
        ipv4_address: 10.5.0.5

  frontend:
    build:
      context: ./Frontend
    ports:
      - "80:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    networks:
      cyber:
        ipv4_address: 10.5.0.6

networks:
  cyber:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
