version: '3'
services:
  backend:
    build:
      context: ./Backend
    ports:
      - "3000:3000"
    networks:
      - my-network

  frontend:
    build:
      context: ./Frontend
    ports:
      - "443:5000"
    enviroment:
      - HOST=0.0.0.0
      - PORT=5000
    networks:
      - my-network

networks:
  my-network:
